name: C/C++ code linter (clang-tidy, clang-format, and cppcheck)
description: Automatically checks pull requests changes with clang-tidy, clang-format, and cppcheck and posts the comment with result.
author: tonybaloney
branding:
  icon: alert-circle
  color: green
inputs:
  path:
    description: 'Project Directory'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
