name: CPPCheck
description: Automatically checks pull requests changes with cppcheck and prints the results as GitHub annotations
author: tonybaloney
branding:
  icon: alert-circle
  color: green
inputs:
  path:
    description: 'Project Directory'
    required: false
    default: '.'
  level:
    description: 'Reporting level (cppcheck --include=<level>'
    required: false
    default: 'warning'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.level }}
